
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NHANVIEN` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NHANVIEN
 * 
 */
export type NHANVIENModel = runtime.Types.Result.DefaultSelection<Prisma.$NHANVIENPayload>

export type AggregateNHANVIEN = {
  _count: NHANVIENCountAggregateOutputType | null
  _avg: NHANVIENAvgAggregateOutputType | null
  _sum: NHANVIENSumAggregateOutputType | null
  _min: NHANVIENMinAggregateOutputType | null
  _max: NHANVIENMaxAggregateOutputType | null
}

export type NHANVIENAvgAggregateOutputType = {
  id: number | null
  stt: number | null
}

export type NHANVIENSumAggregateOutputType = {
  id: number | null
  stt: number | null
}

export type NHANVIENMinAggregateOutputType = {
  id: number | null
  maNv: string | null
  stt: number | null
  hoTen: string | null
  chucVu: string | null
  trinhDo: string | null
  khoaPhong: string | null
  ngayBoNhiem: Date | null
  ngayBoNhiemLai: Date | null
  lyLuanChinhTri: string | null
  qlNhaNuoc: string | null
  qlBenhVien: string | null
  ngoaiNgu: string | null
  tinHoc: string | null
  qpAnNinh: string | null
  ngayBnl: Date | null
  ghiChu: string | null
}

export type NHANVIENMaxAggregateOutputType = {
  id: number | null
  maNv: string | null
  stt: number | null
  hoTen: string | null
  chucVu: string | null
  trinhDo: string | null
  khoaPhong: string | null
  ngayBoNhiem: Date | null
  ngayBoNhiemLai: Date | null
  lyLuanChinhTri: string | null
  qlNhaNuoc: string | null
  qlBenhVien: string | null
  ngoaiNgu: string | null
  tinHoc: string | null
  qpAnNinh: string | null
  ngayBnl: Date | null
  ghiChu: string | null
}

export type NHANVIENCountAggregateOutputType = {
  id: number
  maNv: number
  stt: number
  hoTen: number
  chucVu: number
  trinhDo: number
  khoaPhong: number
  ngayBoNhiem: number
  ngayBoNhiemLai: number
  lyLuanChinhTri: number
  qlNhaNuoc: number
  qlBenhVien: number
  ngoaiNgu: number
  tinHoc: number
  qpAnNinh: number
  ngayBnl: number
  ghiChu: number
  _all: number
}


export type NHANVIENAvgAggregateInputType = {
  id?: true
  stt?: true
}

export type NHANVIENSumAggregateInputType = {
  id?: true
  stt?: true
}

export type NHANVIENMinAggregateInputType = {
  id?: true
  maNv?: true
  stt?: true
  hoTen?: true
  chucVu?: true
  trinhDo?: true
  khoaPhong?: true
  ngayBoNhiem?: true
  ngayBoNhiemLai?: true
  lyLuanChinhTri?: true
  qlNhaNuoc?: true
  qlBenhVien?: true
  ngoaiNgu?: true
  tinHoc?: true
  qpAnNinh?: true
  ngayBnl?: true
  ghiChu?: true
}

export type NHANVIENMaxAggregateInputType = {
  id?: true
  maNv?: true
  stt?: true
  hoTen?: true
  chucVu?: true
  trinhDo?: true
  khoaPhong?: true
  ngayBoNhiem?: true
  ngayBoNhiemLai?: true
  lyLuanChinhTri?: true
  qlNhaNuoc?: true
  qlBenhVien?: true
  ngoaiNgu?: true
  tinHoc?: true
  qpAnNinh?: true
  ngayBnl?: true
  ghiChu?: true
}

export type NHANVIENCountAggregateInputType = {
  id?: true
  maNv?: true
  stt?: true
  hoTen?: true
  chucVu?: true
  trinhDo?: true
  khoaPhong?: true
  ngayBoNhiem?: true
  ngayBoNhiemLai?: true
  lyLuanChinhTri?: true
  qlNhaNuoc?: true
  qlBenhVien?: true
  ngoaiNgu?: true
  tinHoc?: true
  qpAnNinh?: true
  ngayBnl?: true
  ghiChu?: true
  _all?: true
}

export type NHANVIENAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NHANVIEN to aggregate.
   */
  where?: Prisma.NHANVIENWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NHANVIENS to fetch.
   */
  orderBy?: Prisma.NHANVIENOrderByWithRelationInput | Prisma.NHANVIENOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NHANVIENWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NHANVIENS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NHANVIENS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NHANVIENS
  **/
  _count?: true | NHANVIENCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NHANVIENAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NHANVIENSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NHANVIENMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NHANVIENMaxAggregateInputType
}

export type GetNHANVIENAggregateType<T extends NHANVIENAggregateArgs> = {
      [P in keyof T & keyof AggregateNHANVIEN]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNHANVIEN[P]>
    : Prisma.GetScalarType<T[P], AggregateNHANVIEN[P]>
}




export type NHANVIENGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NHANVIENWhereInput
  orderBy?: Prisma.NHANVIENOrderByWithAggregationInput | Prisma.NHANVIENOrderByWithAggregationInput[]
  by: Prisma.NHANVIENScalarFieldEnum[] | Prisma.NHANVIENScalarFieldEnum
  having?: Prisma.NHANVIENScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NHANVIENCountAggregateInputType | true
  _avg?: NHANVIENAvgAggregateInputType
  _sum?: NHANVIENSumAggregateInputType
  _min?: NHANVIENMinAggregateInputType
  _max?: NHANVIENMaxAggregateInputType
}

export type NHANVIENGroupByOutputType = {
  id: number
  maNv: string | null
  stt: number | null
  hoTen: string | null
  chucVu: string | null
  trinhDo: string | null
  khoaPhong: string | null
  ngayBoNhiem: Date | null
  ngayBoNhiemLai: Date | null
  lyLuanChinhTri: string | null
  qlNhaNuoc: string | null
  qlBenhVien: string | null
  ngoaiNgu: string | null
  tinHoc: string | null
  qpAnNinh: string | null
  ngayBnl: Date | null
  ghiChu: string | null
  _count: NHANVIENCountAggregateOutputType | null
  _avg: NHANVIENAvgAggregateOutputType | null
  _sum: NHANVIENSumAggregateOutputType | null
  _min: NHANVIENMinAggregateOutputType | null
  _max: NHANVIENMaxAggregateOutputType | null
}

type GetNHANVIENGroupByPayload<T extends NHANVIENGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NHANVIENGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NHANVIENGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NHANVIENGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NHANVIENGroupByOutputType[P]>
      }
    >
  >



export type NHANVIENWhereInput = {
  AND?: Prisma.NHANVIENWhereInput | Prisma.NHANVIENWhereInput[]
  OR?: Prisma.NHANVIENWhereInput[]
  NOT?: Prisma.NHANVIENWhereInput | Prisma.NHANVIENWhereInput[]
  id?: Prisma.IntFilter<"NHANVIEN"> | number
  maNv?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  stt?: Prisma.IntNullableFilter<"NHANVIEN"> | number | null
  hoTen?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  chucVu?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  trinhDo?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  khoaPhong?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  ngayBoNhiem?: Prisma.DateTimeNullableFilter<"NHANVIEN"> | Date | string | null
  ngayBoNhiemLai?: Prisma.DateTimeNullableFilter<"NHANVIEN"> | Date | string | null
  lyLuanChinhTri?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  qlNhaNuoc?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  qlBenhVien?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  ngoaiNgu?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  tinHoc?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  qpAnNinh?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  ngayBnl?: Prisma.DateTimeNullableFilter<"NHANVIEN"> | Date | string | null
  ghiChu?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
}

export type NHANVIENOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  maNv?: Prisma.SortOrderInput | Prisma.SortOrder
  stt?: Prisma.SortOrderInput | Prisma.SortOrder
  hoTen?: Prisma.SortOrderInput | Prisma.SortOrder
  chucVu?: Prisma.SortOrderInput | Prisma.SortOrder
  trinhDo?: Prisma.SortOrderInput | Prisma.SortOrder
  khoaPhong?: Prisma.SortOrderInput | Prisma.SortOrder
  ngayBoNhiem?: Prisma.SortOrderInput | Prisma.SortOrder
  ngayBoNhiemLai?: Prisma.SortOrderInput | Prisma.SortOrder
  lyLuanChinhTri?: Prisma.SortOrderInput | Prisma.SortOrder
  qlNhaNuoc?: Prisma.SortOrderInput | Prisma.SortOrder
  qlBenhVien?: Prisma.SortOrderInput | Prisma.SortOrder
  ngoaiNgu?: Prisma.SortOrderInput | Prisma.SortOrder
  tinHoc?: Prisma.SortOrderInput | Prisma.SortOrder
  qpAnNinh?: Prisma.SortOrderInput | Prisma.SortOrder
  ngayBnl?: Prisma.SortOrderInput | Prisma.SortOrder
  ghiChu?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type NHANVIENWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  maNv?: string
  AND?: Prisma.NHANVIENWhereInput | Prisma.NHANVIENWhereInput[]
  OR?: Prisma.NHANVIENWhereInput[]
  NOT?: Prisma.NHANVIENWhereInput | Prisma.NHANVIENWhereInput[]
  stt?: Prisma.IntNullableFilter<"NHANVIEN"> | number | null
  hoTen?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  chucVu?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  trinhDo?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  khoaPhong?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  ngayBoNhiem?: Prisma.DateTimeNullableFilter<"NHANVIEN"> | Date | string | null
  ngayBoNhiemLai?: Prisma.DateTimeNullableFilter<"NHANVIEN"> | Date | string | null
  lyLuanChinhTri?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  qlNhaNuoc?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  qlBenhVien?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  ngoaiNgu?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  tinHoc?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  qpAnNinh?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
  ngayBnl?: Prisma.DateTimeNullableFilter<"NHANVIEN"> | Date | string | null
  ghiChu?: Prisma.StringNullableFilter<"NHANVIEN"> | string | null
}, "id" | "maNv">

export type NHANVIENOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  maNv?: Prisma.SortOrderInput | Prisma.SortOrder
  stt?: Prisma.SortOrderInput | Prisma.SortOrder
  hoTen?: Prisma.SortOrderInput | Prisma.SortOrder
  chucVu?: Prisma.SortOrderInput | Prisma.SortOrder
  trinhDo?: Prisma.SortOrderInput | Prisma.SortOrder
  khoaPhong?: Prisma.SortOrderInput | Prisma.SortOrder
  ngayBoNhiem?: Prisma.SortOrderInput | Prisma.SortOrder
  ngayBoNhiemLai?: Prisma.SortOrderInput | Prisma.SortOrder
  lyLuanChinhTri?: Prisma.SortOrderInput | Prisma.SortOrder
  qlNhaNuoc?: Prisma.SortOrderInput | Prisma.SortOrder
  qlBenhVien?: Prisma.SortOrderInput | Prisma.SortOrder
  ngoaiNgu?: Prisma.SortOrderInput | Prisma.SortOrder
  tinHoc?: Prisma.SortOrderInput | Prisma.SortOrder
  qpAnNinh?: Prisma.SortOrderInput | Prisma.SortOrder
  ngayBnl?: Prisma.SortOrderInput | Prisma.SortOrder
  ghiChu?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.NHANVIENCountOrderByAggregateInput
  _avg?: Prisma.NHANVIENAvgOrderByAggregateInput
  _max?: Prisma.NHANVIENMaxOrderByAggregateInput
  _min?: Prisma.NHANVIENMinOrderByAggregateInput
  _sum?: Prisma.NHANVIENSumOrderByAggregateInput
}

export type NHANVIENScalarWhereWithAggregatesInput = {
  AND?: Prisma.NHANVIENScalarWhereWithAggregatesInput | Prisma.NHANVIENScalarWhereWithAggregatesInput[]
  OR?: Prisma.NHANVIENScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NHANVIENScalarWhereWithAggregatesInput | Prisma.NHANVIENScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"NHANVIEN"> | number
  maNv?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
  stt?: Prisma.IntNullableWithAggregatesFilter<"NHANVIEN"> | number | null
  hoTen?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
  chucVu?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
  trinhDo?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
  khoaPhong?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
  ngayBoNhiem?: Prisma.DateTimeNullableWithAggregatesFilter<"NHANVIEN"> | Date | string | null
  ngayBoNhiemLai?: Prisma.DateTimeNullableWithAggregatesFilter<"NHANVIEN"> | Date | string | null
  lyLuanChinhTri?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
  qlNhaNuoc?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
  qlBenhVien?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
  ngoaiNgu?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
  tinHoc?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
  qpAnNinh?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
  ngayBnl?: Prisma.DateTimeNullableWithAggregatesFilter<"NHANVIEN"> | Date | string | null
  ghiChu?: Prisma.StringNullableWithAggregatesFilter<"NHANVIEN"> | string | null
}

export type NHANVIENCreateInput = {
  maNv?: string | null
  stt?: number | null
  hoTen?: string | null
  chucVu?: string | null
  trinhDo?: string | null
  khoaPhong?: string | null
  ngayBoNhiem?: Date | string | null
  ngayBoNhiemLai?: Date | string | null
  lyLuanChinhTri?: string | null
  qlNhaNuoc?: string | null
  qlBenhVien?: string | null
  ngoaiNgu?: string | null
  tinHoc?: string | null
  qpAnNinh?: string | null
  ngayBnl?: Date | string | null
  ghiChu?: string | null
}

export type NHANVIENUncheckedCreateInput = {
  id?: number
  maNv?: string | null
  stt?: number | null
  hoTen?: string | null
  chucVu?: string | null
  trinhDo?: string | null
  khoaPhong?: string | null
  ngayBoNhiem?: Date | string | null
  ngayBoNhiemLai?: Date | string | null
  lyLuanChinhTri?: string | null
  qlNhaNuoc?: string | null
  qlBenhVien?: string | null
  ngoaiNgu?: string | null
  tinHoc?: string | null
  qpAnNinh?: string | null
  ngayBnl?: Date | string | null
  ghiChu?: string | null
}

export type NHANVIENUpdateInput = {
  maNv?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stt?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  hoTen?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chucVu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trinhDo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  khoaPhong?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngayBoNhiem?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ngayBoNhiemLai?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lyLuanChinhTri?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qlNhaNuoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qlBenhVien?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngoaiNgu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tinHoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qpAnNinh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngayBnl?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ghiChu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type NHANVIENUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  maNv?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stt?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  hoTen?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chucVu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trinhDo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  khoaPhong?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngayBoNhiem?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ngayBoNhiemLai?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lyLuanChinhTri?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qlNhaNuoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qlBenhVien?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngoaiNgu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tinHoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qpAnNinh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngayBnl?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ghiChu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type NHANVIENCreateManyInput = {
  id?: number
  maNv?: string | null
  stt?: number | null
  hoTen?: string | null
  chucVu?: string | null
  trinhDo?: string | null
  khoaPhong?: string | null
  ngayBoNhiem?: Date | string | null
  ngayBoNhiemLai?: Date | string | null
  lyLuanChinhTri?: string | null
  qlNhaNuoc?: string | null
  qlBenhVien?: string | null
  ngoaiNgu?: string | null
  tinHoc?: string | null
  qpAnNinh?: string | null
  ngayBnl?: Date | string | null
  ghiChu?: string | null
}

export type NHANVIENUpdateManyMutationInput = {
  maNv?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stt?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  hoTen?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chucVu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trinhDo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  khoaPhong?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngayBoNhiem?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ngayBoNhiemLai?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lyLuanChinhTri?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qlNhaNuoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qlBenhVien?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngoaiNgu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tinHoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qpAnNinh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngayBnl?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ghiChu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type NHANVIENUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  maNv?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stt?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  hoTen?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chucVu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trinhDo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  khoaPhong?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngayBoNhiem?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ngayBoNhiemLai?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lyLuanChinhTri?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qlNhaNuoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qlBenhVien?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngoaiNgu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tinHoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  qpAnNinh?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ngayBnl?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  ghiChu?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type NHANVIENCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  maNv?: Prisma.SortOrder
  stt?: Prisma.SortOrder
  hoTen?: Prisma.SortOrder
  chucVu?: Prisma.SortOrder
  trinhDo?: Prisma.SortOrder
  khoaPhong?: Prisma.SortOrder
  ngayBoNhiem?: Prisma.SortOrder
  ngayBoNhiemLai?: Prisma.SortOrder
  lyLuanChinhTri?: Prisma.SortOrder
  qlNhaNuoc?: Prisma.SortOrder
  qlBenhVien?: Prisma.SortOrder
  ngoaiNgu?: Prisma.SortOrder
  tinHoc?: Prisma.SortOrder
  qpAnNinh?: Prisma.SortOrder
  ngayBnl?: Prisma.SortOrder
  ghiChu?: Prisma.SortOrder
}

export type NHANVIENAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  stt?: Prisma.SortOrder
}

export type NHANVIENMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  maNv?: Prisma.SortOrder
  stt?: Prisma.SortOrder
  hoTen?: Prisma.SortOrder
  chucVu?: Prisma.SortOrder
  trinhDo?: Prisma.SortOrder
  khoaPhong?: Prisma.SortOrder
  ngayBoNhiem?: Prisma.SortOrder
  ngayBoNhiemLai?: Prisma.SortOrder
  lyLuanChinhTri?: Prisma.SortOrder
  qlNhaNuoc?: Prisma.SortOrder
  qlBenhVien?: Prisma.SortOrder
  ngoaiNgu?: Prisma.SortOrder
  tinHoc?: Prisma.SortOrder
  qpAnNinh?: Prisma.SortOrder
  ngayBnl?: Prisma.SortOrder
  ghiChu?: Prisma.SortOrder
}

export type NHANVIENMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  maNv?: Prisma.SortOrder
  stt?: Prisma.SortOrder
  hoTen?: Prisma.SortOrder
  chucVu?: Prisma.SortOrder
  trinhDo?: Prisma.SortOrder
  khoaPhong?: Prisma.SortOrder
  ngayBoNhiem?: Prisma.SortOrder
  ngayBoNhiemLai?: Prisma.SortOrder
  lyLuanChinhTri?: Prisma.SortOrder
  qlNhaNuoc?: Prisma.SortOrder
  qlBenhVien?: Prisma.SortOrder
  ngoaiNgu?: Prisma.SortOrder
  tinHoc?: Prisma.SortOrder
  qpAnNinh?: Prisma.SortOrder
  ngayBnl?: Prisma.SortOrder
  ghiChu?: Prisma.SortOrder
}

export type NHANVIENSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  stt?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type NHANVIENSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  maNv?: boolean
  stt?: boolean
  hoTen?: boolean
  chucVu?: boolean
  trinhDo?: boolean
  khoaPhong?: boolean
  ngayBoNhiem?: boolean
  ngayBoNhiemLai?: boolean
  lyLuanChinhTri?: boolean
  qlNhaNuoc?: boolean
  qlBenhVien?: boolean
  ngoaiNgu?: boolean
  tinHoc?: boolean
  qpAnNinh?: boolean
  ngayBnl?: boolean
  ghiChu?: boolean
}, ExtArgs["result"]["nHANVIEN"]>

export type NHANVIENSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  maNv?: boolean
  stt?: boolean
  hoTen?: boolean
  chucVu?: boolean
  trinhDo?: boolean
  khoaPhong?: boolean
  ngayBoNhiem?: boolean
  ngayBoNhiemLai?: boolean
  lyLuanChinhTri?: boolean
  qlNhaNuoc?: boolean
  qlBenhVien?: boolean
  ngoaiNgu?: boolean
  tinHoc?: boolean
  qpAnNinh?: boolean
  ngayBnl?: boolean
  ghiChu?: boolean
}, ExtArgs["result"]["nHANVIEN"]>

export type NHANVIENSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  maNv?: boolean
  stt?: boolean
  hoTen?: boolean
  chucVu?: boolean
  trinhDo?: boolean
  khoaPhong?: boolean
  ngayBoNhiem?: boolean
  ngayBoNhiemLai?: boolean
  lyLuanChinhTri?: boolean
  qlNhaNuoc?: boolean
  qlBenhVien?: boolean
  ngoaiNgu?: boolean
  tinHoc?: boolean
  qpAnNinh?: boolean
  ngayBnl?: boolean
  ghiChu?: boolean
}, ExtArgs["result"]["nHANVIEN"]>

export type NHANVIENSelectScalar = {
  id?: boolean
  maNv?: boolean
  stt?: boolean
  hoTen?: boolean
  chucVu?: boolean
  trinhDo?: boolean
  khoaPhong?: boolean
  ngayBoNhiem?: boolean
  ngayBoNhiemLai?: boolean
  lyLuanChinhTri?: boolean
  qlNhaNuoc?: boolean
  qlBenhVien?: boolean
  ngoaiNgu?: boolean
  tinHoc?: boolean
  qpAnNinh?: boolean
  ngayBnl?: boolean
  ghiChu?: boolean
}

export type NHANVIENOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "maNv" | "stt" | "hoTen" | "chucVu" | "trinhDo" | "khoaPhong" | "ngayBoNhiem" | "ngayBoNhiemLai" | "lyLuanChinhTri" | "qlNhaNuoc" | "qlBenhVien" | "ngoaiNgu" | "tinHoc" | "qpAnNinh" | "ngayBnl" | "ghiChu", ExtArgs["result"]["nHANVIEN"]>

export type $NHANVIENPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NHANVIEN"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    maNv: string | null
    stt: number | null
    hoTen: string | null
    chucVu: string | null
    trinhDo: string | null
    khoaPhong: string | null
    ngayBoNhiem: Date | null
    ngayBoNhiemLai: Date | null
    lyLuanChinhTri: string | null
    qlNhaNuoc: string | null
    qlBenhVien: string | null
    ngoaiNgu: string | null
    tinHoc: string | null
    qpAnNinh: string | null
    ngayBnl: Date | null
    ghiChu: string | null
  }, ExtArgs["result"]["nHANVIEN"]>
  composites: {}
}

export type NHANVIENGetPayload<S extends boolean | null | undefined | NHANVIENDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload, S>

export type NHANVIENCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NHANVIENFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NHANVIENCountAggregateInputType | true
  }

export interface NHANVIENDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NHANVIEN'], meta: { name: 'NHANVIEN' } }
  /**
   * Find zero or one NHANVIEN that matches the filter.
   * @param {NHANVIENFindUniqueArgs} args - Arguments to find a NHANVIEN
   * @example
   * // Get one NHANVIEN
   * const nHANVIEN = await prisma.nHANVIEN.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NHANVIENFindUniqueArgs>(args: Prisma.SelectSubset<T, NHANVIENFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NHANVIENClient<runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NHANVIEN that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NHANVIENFindUniqueOrThrowArgs} args - Arguments to find a NHANVIEN
   * @example
   * // Get one NHANVIEN
   * const nHANVIEN = await prisma.nHANVIEN.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NHANVIENFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NHANVIENFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NHANVIENClient<runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NHANVIEN that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NHANVIENFindFirstArgs} args - Arguments to find a NHANVIEN
   * @example
   * // Get one NHANVIEN
   * const nHANVIEN = await prisma.nHANVIEN.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NHANVIENFindFirstArgs>(args?: Prisma.SelectSubset<T, NHANVIENFindFirstArgs<ExtArgs>>): Prisma.Prisma__NHANVIENClient<runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NHANVIEN that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NHANVIENFindFirstOrThrowArgs} args - Arguments to find a NHANVIEN
   * @example
   * // Get one NHANVIEN
   * const nHANVIEN = await prisma.nHANVIEN.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NHANVIENFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NHANVIENFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NHANVIENClient<runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NHANVIENS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NHANVIENFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NHANVIENS
   * const nHANVIENS = await prisma.nHANVIEN.findMany()
   * 
   * // Get first 10 NHANVIENS
   * const nHANVIENS = await prisma.nHANVIEN.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const nHANVIENWithIdOnly = await prisma.nHANVIEN.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NHANVIENFindManyArgs>(args?: Prisma.SelectSubset<T, NHANVIENFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NHANVIEN.
   * @param {NHANVIENCreateArgs} args - Arguments to create a NHANVIEN.
   * @example
   * // Create one NHANVIEN
   * const NHANVIEN = await prisma.nHANVIEN.create({
   *   data: {
   *     // ... data to create a NHANVIEN
   *   }
   * })
   * 
   */
  create<T extends NHANVIENCreateArgs>(args: Prisma.SelectSubset<T, NHANVIENCreateArgs<ExtArgs>>): Prisma.Prisma__NHANVIENClient<runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NHANVIENS.
   * @param {NHANVIENCreateManyArgs} args - Arguments to create many NHANVIENS.
   * @example
   * // Create many NHANVIENS
   * const nHANVIEN = await prisma.nHANVIEN.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NHANVIENCreateManyArgs>(args?: Prisma.SelectSubset<T, NHANVIENCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NHANVIENS and returns the data saved in the database.
   * @param {NHANVIENCreateManyAndReturnArgs} args - Arguments to create many NHANVIENS.
   * @example
   * // Create many NHANVIENS
   * const nHANVIEN = await prisma.nHANVIEN.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NHANVIENS and only return the `id`
   * const nHANVIENWithIdOnly = await prisma.nHANVIEN.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NHANVIENCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NHANVIENCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NHANVIEN.
   * @param {NHANVIENDeleteArgs} args - Arguments to delete one NHANVIEN.
   * @example
   * // Delete one NHANVIEN
   * const NHANVIEN = await prisma.nHANVIEN.delete({
   *   where: {
   *     // ... filter to delete one NHANVIEN
   *   }
   * })
   * 
   */
  delete<T extends NHANVIENDeleteArgs>(args: Prisma.SelectSubset<T, NHANVIENDeleteArgs<ExtArgs>>): Prisma.Prisma__NHANVIENClient<runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NHANVIEN.
   * @param {NHANVIENUpdateArgs} args - Arguments to update one NHANVIEN.
   * @example
   * // Update one NHANVIEN
   * const nHANVIEN = await prisma.nHANVIEN.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NHANVIENUpdateArgs>(args: Prisma.SelectSubset<T, NHANVIENUpdateArgs<ExtArgs>>): Prisma.Prisma__NHANVIENClient<runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NHANVIENS.
   * @param {NHANVIENDeleteManyArgs} args - Arguments to filter NHANVIENS to delete.
   * @example
   * // Delete a few NHANVIENS
   * const { count } = await prisma.nHANVIEN.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NHANVIENDeleteManyArgs>(args?: Prisma.SelectSubset<T, NHANVIENDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NHANVIENS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NHANVIENUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NHANVIENS
   * const nHANVIEN = await prisma.nHANVIEN.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NHANVIENUpdateManyArgs>(args: Prisma.SelectSubset<T, NHANVIENUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NHANVIENS and returns the data updated in the database.
   * @param {NHANVIENUpdateManyAndReturnArgs} args - Arguments to update many NHANVIENS.
   * @example
   * // Update many NHANVIENS
   * const nHANVIEN = await prisma.nHANVIEN.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NHANVIENS and only return the `id`
   * const nHANVIENWithIdOnly = await prisma.nHANVIEN.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NHANVIENUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NHANVIENUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NHANVIEN.
   * @param {NHANVIENUpsertArgs} args - Arguments to update or create a NHANVIEN.
   * @example
   * // Update or create a NHANVIEN
   * const nHANVIEN = await prisma.nHANVIEN.upsert({
   *   create: {
   *     // ... data to create a NHANVIEN
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NHANVIEN we want to update
   *   }
   * })
   */
  upsert<T extends NHANVIENUpsertArgs>(args: Prisma.SelectSubset<T, NHANVIENUpsertArgs<ExtArgs>>): Prisma.Prisma__NHANVIENClient<runtime.Types.Result.GetResult<Prisma.$NHANVIENPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NHANVIENS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NHANVIENCountArgs} args - Arguments to filter NHANVIENS to count.
   * @example
   * // Count the number of NHANVIENS
   * const count = await prisma.nHANVIEN.count({
   *   where: {
   *     // ... the filter for the NHANVIENS we want to count
   *   }
   * })
  **/
  count<T extends NHANVIENCountArgs>(
    args?: Prisma.Subset<T, NHANVIENCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NHANVIENCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NHANVIEN.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NHANVIENAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NHANVIENAggregateArgs>(args: Prisma.Subset<T, NHANVIENAggregateArgs>): Prisma.PrismaPromise<GetNHANVIENAggregateType<T>>

  /**
   * Group by NHANVIEN.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NHANVIENGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NHANVIENGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NHANVIENGroupByArgs['orderBy'] }
      : { orderBy?: NHANVIENGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NHANVIENGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNHANVIENGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NHANVIEN model
 */
readonly fields: NHANVIENFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NHANVIEN.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NHANVIENClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NHANVIEN model
 */
export interface NHANVIENFieldRefs {
  readonly id: Prisma.FieldRef<"NHANVIEN", 'Int'>
  readonly maNv: Prisma.FieldRef<"NHANVIEN", 'String'>
  readonly stt: Prisma.FieldRef<"NHANVIEN", 'Int'>
  readonly hoTen: Prisma.FieldRef<"NHANVIEN", 'String'>
  readonly chucVu: Prisma.FieldRef<"NHANVIEN", 'String'>
  readonly trinhDo: Prisma.FieldRef<"NHANVIEN", 'String'>
  readonly khoaPhong: Prisma.FieldRef<"NHANVIEN", 'String'>
  readonly ngayBoNhiem: Prisma.FieldRef<"NHANVIEN", 'DateTime'>
  readonly ngayBoNhiemLai: Prisma.FieldRef<"NHANVIEN", 'DateTime'>
  readonly lyLuanChinhTri: Prisma.FieldRef<"NHANVIEN", 'String'>
  readonly qlNhaNuoc: Prisma.FieldRef<"NHANVIEN", 'String'>
  readonly qlBenhVien: Prisma.FieldRef<"NHANVIEN", 'String'>
  readonly ngoaiNgu: Prisma.FieldRef<"NHANVIEN", 'String'>
  readonly tinHoc: Prisma.FieldRef<"NHANVIEN", 'String'>
  readonly qpAnNinh: Prisma.FieldRef<"NHANVIEN", 'String'>
  readonly ngayBnl: Prisma.FieldRef<"NHANVIEN", 'DateTime'>
  readonly ghiChu: Prisma.FieldRef<"NHANVIEN", 'String'>
}
    

// Custom InputTypes
/**
 * NHANVIEN findUnique
 */
export type NHANVIENFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
  /**
   * Filter, which NHANVIEN to fetch.
   */
  where: Prisma.NHANVIENWhereUniqueInput
}

/**
 * NHANVIEN findUniqueOrThrow
 */
export type NHANVIENFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
  /**
   * Filter, which NHANVIEN to fetch.
   */
  where: Prisma.NHANVIENWhereUniqueInput
}

/**
 * NHANVIEN findFirst
 */
export type NHANVIENFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
  /**
   * Filter, which NHANVIEN to fetch.
   */
  where?: Prisma.NHANVIENWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NHANVIENS to fetch.
   */
  orderBy?: Prisma.NHANVIENOrderByWithRelationInput | Prisma.NHANVIENOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NHANVIENS.
   */
  cursor?: Prisma.NHANVIENWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NHANVIENS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NHANVIENS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NHANVIENS.
   */
  distinct?: Prisma.NHANVIENScalarFieldEnum | Prisma.NHANVIENScalarFieldEnum[]
}

/**
 * NHANVIEN findFirstOrThrow
 */
export type NHANVIENFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
  /**
   * Filter, which NHANVIEN to fetch.
   */
  where?: Prisma.NHANVIENWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NHANVIENS to fetch.
   */
  orderBy?: Prisma.NHANVIENOrderByWithRelationInput | Prisma.NHANVIENOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NHANVIENS.
   */
  cursor?: Prisma.NHANVIENWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NHANVIENS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NHANVIENS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NHANVIENS.
   */
  distinct?: Prisma.NHANVIENScalarFieldEnum | Prisma.NHANVIENScalarFieldEnum[]
}

/**
 * NHANVIEN findMany
 */
export type NHANVIENFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
  /**
   * Filter, which NHANVIENS to fetch.
   */
  where?: Prisma.NHANVIENWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NHANVIENS to fetch.
   */
  orderBy?: Prisma.NHANVIENOrderByWithRelationInput | Prisma.NHANVIENOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NHANVIENS.
   */
  cursor?: Prisma.NHANVIENWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NHANVIENS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NHANVIENS.
   */
  skip?: number
  distinct?: Prisma.NHANVIENScalarFieldEnum | Prisma.NHANVIENScalarFieldEnum[]
}

/**
 * NHANVIEN create
 */
export type NHANVIENCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
  /**
   * The data needed to create a NHANVIEN.
   */
  data?: Prisma.XOR<Prisma.NHANVIENCreateInput, Prisma.NHANVIENUncheckedCreateInput>
}

/**
 * NHANVIEN createMany
 */
export type NHANVIENCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NHANVIENS.
   */
  data: Prisma.NHANVIENCreateManyInput | Prisma.NHANVIENCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NHANVIEN createManyAndReturn
 */
export type NHANVIENCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
  /**
   * The data used to create many NHANVIENS.
   */
  data: Prisma.NHANVIENCreateManyInput | Prisma.NHANVIENCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NHANVIEN update
 */
export type NHANVIENUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
  /**
   * The data needed to update a NHANVIEN.
   */
  data: Prisma.XOR<Prisma.NHANVIENUpdateInput, Prisma.NHANVIENUncheckedUpdateInput>
  /**
   * Choose, which NHANVIEN to update.
   */
  where: Prisma.NHANVIENWhereUniqueInput
}

/**
 * NHANVIEN updateMany
 */
export type NHANVIENUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NHANVIENS.
   */
  data: Prisma.XOR<Prisma.NHANVIENUpdateManyMutationInput, Prisma.NHANVIENUncheckedUpdateManyInput>
  /**
   * Filter which NHANVIENS to update
   */
  where?: Prisma.NHANVIENWhereInput
  /**
   * Limit how many NHANVIENS to update.
   */
  limit?: number
}

/**
 * NHANVIEN updateManyAndReturn
 */
export type NHANVIENUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
  /**
   * The data used to update NHANVIENS.
   */
  data: Prisma.XOR<Prisma.NHANVIENUpdateManyMutationInput, Prisma.NHANVIENUncheckedUpdateManyInput>
  /**
   * Filter which NHANVIENS to update
   */
  where?: Prisma.NHANVIENWhereInput
  /**
   * Limit how many NHANVIENS to update.
   */
  limit?: number
}

/**
 * NHANVIEN upsert
 */
export type NHANVIENUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
  /**
   * The filter to search for the NHANVIEN to update in case it exists.
   */
  where: Prisma.NHANVIENWhereUniqueInput
  /**
   * In case the NHANVIEN found by the `where` argument doesn't exist, create a new NHANVIEN with this data.
   */
  create: Prisma.XOR<Prisma.NHANVIENCreateInput, Prisma.NHANVIENUncheckedCreateInput>
  /**
   * In case the NHANVIEN was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NHANVIENUpdateInput, Prisma.NHANVIENUncheckedUpdateInput>
}

/**
 * NHANVIEN delete
 */
export type NHANVIENDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
  /**
   * Filter which NHANVIEN to delete.
   */
  where: Prisma.NHANVIENWhereUniqueInput
}

/**
 * NHANVIEN deleteMany
 */
export type NHANVIENDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NHANVIENS to delete
   */
  where?: Prisma.NHANVIENWhereInput
  /**
   * Limit how many NHANVIENS to delete.
   */
  limit?: number
}

/**
 * NHANVIEN without action
 */
export type NHANVIENDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NHANVIEN
   */
  select?: Prisma.NHANVIENSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NHANVIEN
   */
  omit?: Prisma.NHANVIENOmit<ExtArgs> | null
}
