
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * Please import the `PrismaClient` class from the `client.ts` file instead.
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "./prismaNamespace"


const config: runtime.GetPrismaClientConfig = {
  "previewFeatures": [],
  "clientVersion": "7.2.0",
  "engineVersion": "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3",
  "activeProvider": "postgresql",
  "inlineSchema": "// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ngenerator client {\n  provider = \"prisma-client\"\n  output   = \"../prisma/client\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n}\n\nmodel NHANVIEN {\n  id             Int       @id @default(autoincrement())\n  maNv           String?   @unique @map(\"ma_nv\")\n  stt            Int?\n  hoTen          String?   @map(\"ho_ten\")\n  chucVu         String?   @map(\"chuc_vu\")\n  trinhDo        String?   @map(\"trinh_do\")\n  khoaPhong      String?   @map(\"khoa_phong\")\n  ngayBoNhiem    DateTime? @map(\"ngay_bo_nhiem\")\n  ngayBoNhiemLai DateTime? @map(\"ngay_bo_nhiem_lai\")\n  lyLuanChinhTri String?   @map(\"ly_luan_chinh_tri\")\n  qlNhaNuoc      String?   @map(\"ql_nha_nuoc\")\n  qlBenhVien     String?   @map(\"ql_benh_vien\")\n  ngoaiNgu       String?   @map(\"ngoai_ngu\")\n  tinHoc         String?   @map(\"tin_hoc\")\n  qpAnNinh       String?   @map(\"qp_an_ninh\")\n  ngayBnl        DateTime? @map(\"ngay_bnl\")\n  ghiChu         String?   @map(\"ghi_chu\")\n\n  @@map(\"nhan_vien\")\n}\n",
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  }
}

config.runtimeDataModel = JSON.parse("{\"models\":{\"NHANVIEN\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"maNv\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"ma_nv\"},{\"name\":\"stt\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"hoTen\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"ho_ten\"},{\"name\":\"chucVu\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"chuc_vu\"},{\"name\":\"trinhDo\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"trinh_do\"},{\"name\":\"khoaPhong\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"khoa_phong\"},{\"name\":\"ngayBoNhiem\",\"kind\":\"scalar\",\"type\":\"DateTime\",\"dbName\":\"ngay_bo_nhiem\"},{\"name\":\"ngayBoNhiemLai\",\"kind\":\"scalar\",\"type\":\"DateTime\",\"dbName\":\"ngay_bo_nhiem_lai\"},{\"name\":\"lyLuanChinhTri\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"ly_luan_chinh_tri\"},{\"name\":\"qlNhaNuoc\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"ql_nha_nuoc\"},{\"name\":\"qlBenhVien\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"ql_benh_vien\"},{\"name\":\"ngoaiNgu\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"ngoai_ngu\"},{\"name\":\"tinHoc\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"tin_hoc\"},{\"name\":\"qpAnNinh\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"qp_an_ninh\"},{\"name\":\"ngayBnl\",\"kind\":\"scalar\",\"type\":\"DateTime\",\"dbName\":\"ngay_bnl\"},{\"name\":\"ghiChu\",\"kind\":\"scalar\",\"type\":\"String\",\"dbName\":\"ghi_chu\"}],\"dbName\":\"nhan_vien\"}},\"enums\":{},\"types\":{}}")

async function decodeBase64AsWasm(wasmBase64: string): Promise<WebAssembly.Module> {
  const { Buffer } = await import('node:buffer')
  const wasmArray = Buffer.from(wasmBase64, 'base64')
  return new WebAssembly.Module(wasmArray)
}

config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_bg.postgresql.mjs"),

  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_bg.postgresql.wasm-base64.mjs")
    return await decodeBase64AsWasm(wasm)
  }
}



export type LogOptions<ClientOptions extends Prisma.PrismaClientOptions> =
  'log' extends keyof ClientOptions ? ClientOptions['log'] extends Array<Prisma.LogLevel | Prisma.LogDefinition> ? Prisma.GetEvents<ClientOptions['log']> : never : never

export interface PrismaClientConstructor {
    /**
   * ## Prisma Client
   * 
   * Type-safe database client for TypeScript
   * @example
   * ```
   * const prisma = new PrismaClient()
   * // Fetch zero or more NHANVIENS
   * const nHANVIENS = await prisma.nHANVIEN.findMany()
   * ```
   * 
   * Read more in our [docs](https://pris.ly/d/client).
   */

  new <
    Options extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions,
    LogOpts extends LogOptions<Options> = LogOptions<Options>,
    OmitOpts extends Prisma.PrismaClientOptions['omit'] = Options extends { omit: infer U } ? U : Prisma.PrismaClientOptions['omit'],
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
  >(options: Prisma.Subset<Options, Prisma.PrismaClientOptions> ): PrismaClient<LogOpts, OmitOpts, ExtArgs>
}

/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more NHANVIENS
 * const nHANVIENS = await prisma.nHANVIEN.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */

export interface PrismaClient<
  in LogOpts extends Prisma.LogLevel = never,
  in out OmitOpts extends Prisma.PrismaClientOptions['omit'] = undefined,
  in out ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['other'] }

  $on<V extends LogOpts>(eventType: V, callback: (event: V extends 'query' ? Prisma.QueryEvent : Prisma.LogEvent) => void): PrismaClient;

  /**
   * Connect with the database
   */
  $connect(): runtime.Types.Utils.JsPromise<void>;

  /**
   * Disconnect from the database
   */
  $disconnect(): runtime.Types.Utils.JsPromise<void>;

/**
   * Executes a prepared raw query and returns the number of affected rows.
   * @example
   * ```
   * const result = await prisma.$executeRaw`UPDATE User SET cool = ${true} WHERE email = ${'user@email.com'};`
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $executeRaw<T = unknown>(query: TemplateStringsArray | Prisma.Sql, ...values: any[]): Prisma.PrismaPromise<number>;

  /**
   * Executes a raw query and returns the number of affected rows.
   * Susceptible to SQL injections, see documentation.
   * @example
   * ```
   * const result = await prisma.$executeRawUnsafe('UPDATE User SET cool = $1 WHERE email = $2 ;', true, 'user@email.com')
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $executeRawUnsafe<T = unknown>(query: string, ...values: any[]): Prisma.PrismaPromise<number>;

  /**
   * Performs a prepared raw query and returns the `SELECT` data.
   * @example
   * ```
   * const result = await prisma.$queryRaw`SELECT * FROM User WHERE id = ${1} OR email = ${'user@email.com'};`
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $queryRaw<T = unknown>(query: TemplateStringsArray | Prisma.Sql, ...values: any[]): Prisma.PrismaPromise<T>;

  /**
   * Performs a raw query and returns the `SELECT` data.
   * Susceptible to SQL injections, see documentation.
   * @example
   * ```
   * const result = await prisma.$queryRawUnsafe('SELECT * FROM User WHERE id = $1 OR email = $2;', 1, 'user@email.com')
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $queryRawUnsafe<T = unknown>(query: string, ...values: any[]): Prisma.PrismaPromise<T>;


  /**
   * Allows the running of a sequence of read/write operations that are guaranteed to either succeed or fail as a whole.
   * @example
   * ```
   * const [george, bob, alice] = await prisma.$transaction([
   *   prisma.user.create({ data: { name: 'George' } }),
   *   prisma.user.create({ data: { name: 'Bob' } }),
   *   prisma.user.create({ data: { name: 'Alice' } }),
   * ])
   * ```
   * 
   * Read more in our [docs](https://www.prisma.io/docs/concepts/components/prisma-client/transactions).
   */
  $transaction<P extends Prisma.PrismaPromise<any>[]>(arg: [...P], options?: { isolationLevel?: Prisma.TransactionIsolationLevel }): runtime.Types.Utils.JsPromise<runtime.Types.Utils.UnwrapTuple<P>>

  $transaction<R>(fn: (prisma: Omit<PrismaClient, runtime.ITXClientDenyList>) => runtime.Types.Utils.JsPromise<R>, options?: { maxWait?: number, timeout?: number, isolationLevel?: Prisma.TransactionIsolationLevel }): runtime.Types.Utils.JsPromise<R>

  $extends: runtime.Types.Extensions.ExtendsHook<"extends", Prisma.TypeMapCb<OmitOpts>, ExtArgs, runtime.Types.Utils.Call<Prisma.TypeMapCb<OmitOpts>, {
    extArgs: ExtArgs
  }>>

      /**
   * `prisma.nHANVIEN`: Exposes CRUD operations for the **NHANVIEN** model.
    * Example usage:
    * ```ts
    * // Fetch zero or more NHANVIENS
    * const nHANVIENS = await prisma.nHANVIEN.findMany()
    * ```
    */
  get nHANVIEN(): Prisma.NHANVIENDelegate<ExtArgs, { omit: OmitOpts }>;
}

export function getPrismaClientClass(): PrismaClientConstructor {
  return runtime.getPrismaClient(config) as unknown as PrismaClientConstructor
}
